# Setup
title:               jMinimal
tagline:             'simply works ~ modified'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Codanv
  url:               https://github.com/Codanv
  email:             ''

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
